### ISSUE TITLE
Issue Using the Search Feature in CC-CEDICT Add-on

### ISSUE THREAD

**Issue by S-Downes** [ThoreBor/CC-CEDICT-for-Anki#30]
I was searching some words close to their Pinyin form, but not exact, leading to an error as shown. 

![image](https://user-images.githubusercontent.com/36989702/171460374-6a33284d-54ca-4dc4-8b47-192c2a482f8a.png)

Full debug info:

```
Debug info:
Anki 2.1.53 (96bacf79) Python 3.9.7 Qt 5.15.2 PyQt 5.15.5
Platform: Windows 10
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2022-06-01 17:51:41
```

```
Caught exception:
Traceback (most recent call last):
  File "C:\Users\D\AppData\Roaming\Anki2\addons21\418828045\cedict\main.py", line 255, in search
    self.exact_match(query, "eng")
  File "C:\Users\D\AppData\Roaming\Anki2\addons21\418828045\cedict\main.py", line 210, in exact_match
    self.first_result()
  File "C:\Users\D\AppData\Roaming\Anki2\addons21\418828045\cedict\main.py", line 268, in first_result
    simp = self.dialog.Results.item(0, 0).text()
AttributeError: 'NoneType' object has no attribute 'text'
```

```
Caught exception:
Traceback (most recent call last):
  File "C:\Users\D\AppData\Roaming\Anki2\addons21\418828045\cedict\main.py", line 255, in search
    self.exact_match(query, "eng")
  File "C:\Users\D\AppData\Roaming\Anki2\addons21\418828045\cedict\main.py", line 210, in exact_match
    self.first_result()
  File "C:\Users\D\AppData\Roaming\Anki2\addons21\418828045\cedict\main.py", line 268, in first_result
    simp = self.dialog.Results.item(0, 0).text()
AttributeError: 'NoneType' object has no attribute 'text'
```

The word being searched in this image is dian. Searching for an English word (shop) works fine.

**Comment by ThoreBor** [comment]
Using pinyin to search is currently not supported, but I'll add it in the future. If you use the newest version, you shouldn't get an error though.

**Comment by S-Downes** [comment]
Understood. As for errors in the latest version, I just updated Anki today to check:

> Debug info:
Anki 2.1.54 (b6a7760c) Python 3.9.7 Qt 5.15.2 PyQt 5.15.5
Platform: Windows 10
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2022-07-19 


The same error still shows however.
