### ISSUE TITLE
Something doesn´t work, I dont know if it´s my fault

### ISSUE THREAD

**Issue by Kat-ii** [ThoreBor/CC-CEDICT-for-Anki#33]
Debug info:
Anki 2.1.44 (b2b3275f) Python 3.8.6 Qt 5.14.2 PyQt 5.14.2
Platform: Mac 10.16
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2022-08-12 20:06:34
Add-ons possibly involved: ⁨CC-CEDICT for Anki Chinese dictionary⁩

Caught exception:
Traceback (most recent call last):
  File "/Users/kati/Library/Application Support/Anki2/addons21/418828045/cedict/main.py", line 382, in init_add
    self.add_note([simp, trad, pinyin, english], input_type, tags)
  File "/Users/kati/Library/Application Support/Anki2/addons21/418828045/cedict/main.py", line 325, in add_note
    n.add_tag(tags)
AttributeError: 'Note' object has no attribute 'add_tag'

**Comment by ThoreBor** [comment]
I think it's because you're using Anki 2.1.44. If you update to a newer version it should work.
